[build]
  command = "npm run build"
  publish = "build"
  functions = "functions"

[dev]
  command = "npm start"
  functions = "functions"
  port = 8888

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200